import type { Track } from './types'

export const awsMlaTrack: Track = {
  id: 'aws-mla',
  label: 'AWS MLA',
  emoji: '☁️',
  description: 'AWS Machine Learning Associate certification track',
  color: 'amber',
  phases: [
    {
      id: 'phase-1-foundations',
      title: 'ML Foundations',
      description: 'Core ML concepts and AWS ML services',
      modules: [
        {
          id: 'aws-ml-basics',
          title: 'AWS ML Basics',
          description: 'Introduction to AWS ML services and core concepts',
          difficulty: 'beginner',
          timeEstimate: '2w',
          xpReward: 10,
          tags: ['aws', 'ml', 'sagemaker'],
          resources: [
            {
              topic: 'AWS ML Docs',
              free: 'https://aws.amazon.com/sagemaker/',
              deliverable: 'Set up SageMaker notebook instance',
            },
          ],
          deliverables: ['Set up SageMaker notebook', 'Run sample Jupyter notebook'],
        },
        {
          id: 'data-prep-aws',
          title: 'Data Preparation on AWS',
          description: 'Data preprocessing for ML on AWS',
          difficulty: 'beginner',
          timeEstimate: '2w',
          xpReward: 10,
          tags: ['aws', 'data-prep', 's3', 'glue'],
          deliverables: ['Create S3 bucket for ML data', 'Run Glue job for data catalog'],
        },
      ],
    },
    {
      id: 'phase-2-model-building',
      title: 'Model Building',
      description: 'Building and training models on AWS',
      modules: [
        {
          id: 'sagemaker-training',
          title: 'SageMaker Model Training',
          description: 'Train ML models using SageMaker',
          difficulty: 'intermediate',
          timeEstimate: '3w',
          xpReward: 25,
          tags: ['sagemaker', 'training', 'ml'],
          deliverables: ['Train XGBoost model on SageMaker', 'Tune hyperparameters'],
        },
        {
          id: 'model-evaluation',
          title: 'Model Evaluation',
          description: 'Evaluate and validate ML models on AWS',
          difficulty: 'intermediate',
          timeEstimate: '2w',
          xpReward: 25,
          tags: ['evaluation', 'ml', 'sagemaker'],
          deliverables: ['Evaluate model performance', 'Generate evaluation report'],
        },
      ],
    },
    {
      id: 'phase-3-deployment',
      title: 'Model Deployment',
      description: 'Deploy and monitor ML models on AWS',
      modules: [
        {
          id: 'sagemaker-endpoints',
          title: 'SageMaker Endpoints',
          description: 'Deploy models as SageMaker endpoints',
          difficulty: 'intermediate',
          timeEstimate: '3w',
          xpReward: 25,
          tags: ['deployment', 'sagemaker', 'endpoints'],
          deliverables: ['Deploy model to SageMaker endpoint', 'Test inference latency'],
        },
        {
          id: 'model-monitoring',
          title: 'Model Monitoring',
          description: 'Monitor deployed models for drift and performance',
          difficulty: 'advanced',
          timeEstimate: '3w',
          xpReward: 50,
          tags: ['monitoring', 'sagemaker', 'devops'],
          deliverables: ['Set up SageMaker Model Monitor', 'Create CloudWatch dashboard'],
        },
      ],
    },
    {
      id: 'phase-4-workflow',
      title: 'ML Workflow',
      description: 'End-to-end ML workflows and best practices',
      modules: [
        {
          id: 'ml-pipeline',
          title: 'ML Pipeline Design',
          description: 'Design end-to-end ML pipelines on AWS',
          difficulty: 'advanced',
          timeEstimate: '4w',
          xpReward: 50,
          tags: ['pipeline', 'step-functions', 'mlops'],
          deliverables: ['Design ML pipeline with Step Functions', 'Automate retraining workflow'],
        },
        {
          id: 'cost-optimization',
          title: 'Cost Optimization',
          description: 'Optimize AWS ML costs',
          difficulty: 'intermediate',
          timeEstimate: '2w',
          xpReward: 25,
          tags: ['cost', 'aws', 'budgets'],
          deliverables: ['Analyze ML spend', 'Implement cost-saving measures'],
        },
      ],
    },
  ],
}
