import type { Track } from './types'

export const csAiTrack: Track = {
  id: 'cs-ai',
  label: 'CS/AI',
  emoji: '🤖',
  description: 'Core computer science and artificial intelligence curriculum with MDX modules',
  color: 'indigo',
  phases: [
    {
      id: 'phase-1-math',
      title: 'Math Aplicada',
      description: 'Applied mathematics foundations for machine learning',
      modules: [
        {
          id: 'optimization-convexa',
          mdxSlug: 'optimization-convexa',
          notebooklmId: 'optimization-convexa',
          title: 'Optimización Convexa para ML',
          description: 'Implementa SGD, Newton y Adam desde cero',
          difficulty: 'intermediate',
          timeEstimate: '3w',
          xpReward: 25,
          tags: ['optimization', 'convex', 'gradient-descent', 'adam', 'numpy'],
        },
        {
          id: 'probabilidad-aplicada',
          mdxSlug: 'probabilidad-aplicada',
          notebooklmId: 'probabilidad-aplicada',
          title: 'Probabilidad Aplicada',
          description: 'Applied probability for ML systems',
          difficulty: 'intermediate',
          timeEstimate: '3w',
          xpReward: 25,
          tags: ['probability', 'statistics', 'ml'],
        },
        {
          id: 'algebra-lineal-numerica',
          mdxSlug: 'algebra-lineal-numerica',
          notebooklmId: 'algebra-lineal-numerica',
          title: 'Álgebra Lineal Numérica',
          description: 'Numerical linear algebra for ML',
          difficulty: 'intermediate',
          timeEstimate: '3w',
          xpReward: 25,
          tags: ['linear-algebra', 'numerical', 'numpy'],
        },
        {
          id: 'calculo-para-ml',
          mdxSlug: 'calculo-para-ml',
          notebooklmId: 'calculo-para-ml',
          title: 'Cálculo para ML',
          description: 'Calculus fundamentals for machine learning',
          difficulty: 'intermediate',
          timeEstimate: '3w',
          xpReward: 25,
          tags: ['calculus', 'ml', 'derivatives'],
        },
      ],
    },
    {
      id: 'phase-2-systems-ai',
      title: 'Systems + AI',
      description: 'Core systems and introductory AI concepts',
      modules: [
        {
          id: 'csapp-memory',
          mdxSlug: 'csapp-memory',
          title: 'CSAPP: Memory',
          description: 'Memory systems and management',
          difficulty: 'intermediate',
          timeEstimate: '3w',
          xpReward: 25,
          tags: ['systems', 'memory', 'csapp'],
        },
        {
          id: 'os-concurrency',
          mdxSlug: 'os-concurrency',
          title: 'OS Concurrency',
          description: 'Operating system concurrency models',
          difficulty: 'intermediate',
          timeEstimate: '3w',
          xpReward: 25,
          tags: ['os', 'concurrency', 'threads'],
        },
        {
          id: 'ml-fundamentals',
          mdxSlug: 'ml-fundamentals',
          title: 'ML Fundamentals desde Cero',
          description: 'Core machine learning fundamentals',
          difficulty: 'intermediate',
          timeEstimate: '4w',
          xpReward: 25,
          tags: ['ml', 'logistic-regression', 'svm', 'cross-validation'],
        },
        {
          id: 'dl-basics-cnn',
          mdxSlug: 'dl-basics-cnn',
          title: 'DL Basics CNN',
          description: 'Deep learning basics with CNNs',
          difficulty: 'intermediate',
          timeEstimate: '4w',
          xpReward: 25,
          tags: ['deep-learning', 'cnn', 'tensorflow'],
        },
        {
          id: 'mlops-intro',
          mdxSlug: 'mlops-intro',
          title: 'MLOps Intro',
          description: 'Introduction to ML operations',
          difficulty: 'intermediate',
          timeEstimate: '4w',
          xpReward: 25,
          tags: ['mlops', 'devops', 'ml'],
        },
      ],
    },
    {
      id: 'phase-3-advanced-ai',
      title: 'Advanced AI',
      description: 'Advanced AI and ML systems',
      modules: [
        {
          id: 'distributed-raft',
          mdxSlug: 'distributed-raft',
          title: 'Distributed Raft',
          description: 'Distributed consensus algorithms',
          difficulty: 'advanced',
          timeEstimate: '3w',
          xpReward: 50,
          tags: ['distributed-systems', 'raft', 'consensus'],
        },
        {
          id: 'advanced-inference-system',
          mdxSlug: 'advanced-inference-system',
          title: 'Advanced Inference System',
          description: 'High-performance ML inference systems',
          difficulty: 'advanced',
          timeEstimate: '3w',
          xpReward: 50,
          tags: ['inference', 'optimization', 'systems'],
        },
        {
          id: 'nlp-finetuning',
          mdxSlug: 'nlp-finetuning',
          notebooklmId: 'nlp-finetuning',
          title: 'NLP Finetuning',
          description: 'Fine-tuning NLP models',
          difficulty: 'advanced',
          timeEstimate: '3w',
          xpReward: 50,
          tags: ['nlp', 'fine-tuning', 'transformers'],
        },
        {
          id: 'mlops-advanced',
          mdxSlug: 'mlops-advanced',
          title: 'MLOps Advanced',
          description: 'Advanced MLOps practices',
          difficulty: 'advanced',
          timeEstimate: '3w',
          xpReward: 50,
          tags: ['mlops', 'production', 'monitoring'],
        },
      ],
    },
    {
      id: 'phase-4-integration',
      title: 'Integration',
      description: 'Ongoing projects and technical writing',
      modules: [],
    },
  ],
}
