import type { Track } from './types'

export const englishTrack: Track = {
  id: 'english',
  label: 'English',
  emoji: '🇬🇧',
  description: 'Native-level C1-C2 English — educated, confident, precise',
  color: 'blue',
  phases: [
    {
      id: 'phase-0-pronunciation',
      title: 'Pronunciation & Fluency',
      description: 'Sound like a well-educated native speaker — C1-C2 target',
      modules: [
        {
          id: 'pronunciation',
          mdxSlug: 'english/pronunciation',
          notebooklmId: 'f270363e-a7c3-4687-980b-b7de944d1fe8',
          title: 'Pronunciation — Native C1-C2',
          description: 'Neutral accent, natural rhythm, confident delivery — educated native standard',
          difficulty: 'intermediate',
          timeEstimate: '4w',
          xpReward: 60,
          tags: ['english', 'pronunciation', 'c1-c2', 'native', 'speaking'],
          deliverables: [
            "Shadow Rachel's English 15 min/day for 2 weeks",
            'Record 2 min speech → analyze pronunciation gaps',
            'Master 10 minimal pairs (v/b, th, ʃ/s, æ/ɛ)',
          ],
        },
      ],
    },
    {
      id: 'phase-1-writing',
      title: 'Technical Writing (C1-C2)',
      description: 'Write with precision and authority — technical docs, PRs, papers',
      modules: [
        {
          id: 'pr-comments',
          mdxSlug: 'english/pr-comments',
          notebooklmId: '49beed51-3ab5-42d5-9576-431c2895cbd6',
          title: 'PR Comments & Technical Writing',
          description: 'Write clear, precise, authoritative technical English',
          difficulty: 'intermediate',
          timeEstimate: '2w',
          xpReward: 25,
          tags: ['english', 'writing', 'pr', 'technical'],
          deliverables: ['Write 5 PR comments for open-source repos in fluent English'],
        },
        {
          id: 'paper-reading',
          mdxSlug: 'english/paper-reading',
          notebooklmId: '6efafee1-ff60-48e3-b4f5-9bc8a5425659',
          title: 'Paper Reading (ML/AI Research)',
          description: 'Read ML papers at native academic English level — no dictionary needed',
          difficulty: 'advanced',
          timeEstimate: '3w',
          xpReward: 50,
          tags: ['english', 'papers', 'research', 'c2'],
          deliverables: [
            'Read Attention Is All You Need + LoRA — no dictionary',
            'Write 500-word summary of each in academic English',
          ],
        },
      ],
    },
    {
      id: 'phase-2-speaking',
      title: 'Speaking & Confidence',
      description: 'Speak like an educated professional — interviews, talks, conversation',
      modules: [
        {
          id: 'interview-prep',
          mdxSlug: 'english/interview-prep',
          notebooklmId: '7123b275-49a7-486b-a208-c629d469f387',
          title: 'Interview Prep',
          description: 'Technical and behavioral interviews — confident, articulate, native-level',
          difficulty: 'intermediate',
          timeEstimate: '3w',
          xpReward: 25,
          tags: ['english', 'interview', 'speaking', 'c1-c2'],
          deliverables: ['Record 3 STAR answers — no fillers, no accent issues'],
        },
        {
          id: 'ollama-review',
          mdxSlug: 'english/ollama-review',
          notebooklmId: '8162c3e2-795e-4db4-8120-a734b60ca5ec',
          title: 'Ollama Review',
          description: 'Write a technical review of Ollama — native English writing',
          difficulty: 'beginner',
          timeEstimate: '1w',
          xpReward: 10,
          tags: ['english', 'ollama', 'writing', 'review'],
          deliverables: ['500-word Ollama review in fluent technical English'],
        },
      ],
    },
  ],
}
